### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MellonBunnu** [coderman64/motobug-engine#3]
How do you jump???
Also can you add a way to edit levels and get the level code?

**Comment by seanmorris** [comment]
a key is jump

**Comment by coderman64** [comment]
This is meant to mirror the default key mapping for Sonic Mania on the PC. At some point, I want to make a system to allow users to remap the buttons, but I haven't gotten around to that yet. 
If you (or anyone else reading this thread) is feeling technically inclined, feel free to work on this and create a pull request! I created an issue for it (#5).
